
export const FETCH_SCHEDULES_REQUEST= 'FETCH_SCHEDULES_REQUEST';
export const FETCH_SCHEDULES_SUCCESS='FETCH_SCHEDULES_SUCCESS';
export const FETCH_SCHEDULES_FAIL='FETCH_SCHEDULES_FAIL';
export const POST_SUCCESS='POST_SUCCESS';
export const POST_FAIL='POST_FAIL';
export const EDIT= 'EDIT';
export const REMOVE_SCHEDULE='REMOVE_SCHEDULE';